---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: <cluster-name>
  region: eu-central-1
vpc:
  subnets:
    private:
      routable-1: { id: <routable-0> }
      routable-2: { id: <routable-1> }
      routable-3: { id: <routable-2> }
      non-routable-1: { id: <non-routable-0> }
      non-routable-2: { id: <non-routable-1> }
      non-routable-3: { id: <non-routable-2> }
iam:
  withOIDC: true
nodeGroups:
  - name: <cluster-name>-ng
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    subnets:
      - <non-routable-0>
      - <non-routable-1>
      - <non-routable-2>
    volumeSize: 80
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
secretsEncryption:
  # KMS key used for envelope encryption of Kubernetes secrets
  keyARN: <key-arn>
