apiVersion: v1
kind: Secret
metadata:
  name: <cluster-name>-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: <repo-url>
  password: <github-token>
  username: admin